name: Build LineageOS with MicroG

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk repo bc bison build-essential curl flex g++-multilib gcc-multilib git-core gnupg gperf imagemagick liblz4-tool libncurses5-dev libncurses-dev libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev wget

    - name: Initialize repo
      run: |
        mkdir -p ~/android/lineage
        cd ~/android/lineage
        repo init -u https://github.com/Ghosterers/Nuxing-OS.git -b lineage-20.0
        repo sync --force-sync -j$(nproc)

    - name: Add MicroG, Aurora Store, Firefox
      run: |
        chmod +x ./scripts/add-prebuilt-apks.sh
        ./scripts/add-prebuilt-apks.sh

    - name: Build LineageOS
      run: |
        cd ~/android/lineage
        source build/envsetup.sh
        lunch lineage_x86_64-eng
        make bacon -j$(nproc)

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: lineageos-build
        path: ~/android/lineage/out/target/product/generic_x86_64/*.zip